### ISSUE TITLE
About the resolution of training

### ISSUE THREAD

**Issue by YuqingWang1029** [obvious-research/phenaki-cvivit#2]
Hi @obvious-research , thanks for your awesome work! I want to ask in what resolution did you train the model. I saw 128 in the config, did you train the model using the specific resolution or mixed resolutions? Will you provide the models with higher resolutions? Thanks!

**Comment by obvious-research** [comment]
Hey! Yes the model is trained with a resolution of 128*128. It is one of our goal to train a version with higher resolution, however for now we are focused on reproducing Phenaki, so that won't be very soon, sorry!

**Comment by YuqingWang1029** [comment]
Hi @obvious-research, thanks for your prompt response! I wonder whether the code and parameters of the repo support the same config for training? How to do the training on my own data? thank you very much !

**Comment by obvious-research** [comment]
Basically you would have to modify the architecture of the model. It is doable but would require a bit of work.

**Comment by YuqingWang1029** [comment]
Thanks for your kindly response!
