### ISSUE TITLE
i3d feature size for videos with more than 15 frames

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [obvious-research/phenaki-cvivit#5]
Hi, I'm currently working with the i3d loss and have observed a potential issue.

For videos with less than 15 frames, the i3d feature size is [bsz, dim, 1, 1, 1] (see https://github.com/obvious-research/phenaki-cvivit/blob/main/phenaki_pytorch/cvivit.py#L273). 

However, for videos with more than 15 frames, the i3d feature size becomes [bsz, dim, >1, 1, 1], which will cause a dimension-mismatch-error in https://github.com/obvious-research/phenaki-cvivit/blob/main/phenaki_pytorch/cvivit.py#L274.

I wonder if I can only use videos with less than 15 frames? Or can I just modify the code from `features = features.reshape((b, features.shape[1]))` to `features = features.reshape((b, -1))`?

**Comment by obvious-research** [comment]
In our case we only used videos of 11 frames, so in fact we did not encounter this error. I think you can just modify the code like you suggested.
